#!/bin/sh

out=$1

function message() {
  mv $out $out.tmp
  cat <<EOS > $out
$1
EOS
  cat $out.tmp >> $out
}

str=$(cat <<-EOS

🐛 :bug: fix bugs
👍 :+1: improve function
✨ :sparkles: add new function
♻️  :recycle: refactoring
🚿 :shower: delete unused function
💚 :green_heart: improve tests / CI
👕 :shirt: fix Lint error / fix code style
🚀 :rocket: improve performance
🆙 :up: update package information or libraries
EOS
)
emoji=$(echo "${str}" | fzf | awk 'match($0, /(:.*:)/) {print substr($0, RSTART, RLENGTH)}')
if [ -n "${emoji}" ]; then
  message ${emoji}
fi
